name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        env:
          TEST_NAME: Daily
        with:
          bootstrap: FrontEnd/mini-inventory-and-sales-management-system/vendor/autoload.php
          configuration: FrontEnd/mini-inventory-and-sales-management-system/test/phpunit.xml
          args: --coverage-text
