on: push
name: CI
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps: 
      - name: Descargar codigo
        uses: actions/checkout@v2
      - name: Correr Unit Test
        run: echo "DB \n Amount of vat \n Is phone number \n Is real name \n Is fake name \nIs email \nIs not email \nEncrypt password \nGet file error message \n Discount amount \nIs url \nGet second file error message"
        
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.3
 
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
 
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
 
    - name: Install composer dependencies
      run: |
        cd FrontEnd/mini-inventory-and-sales-management-system
        composer install --prefer-dist
